In [15]:
!pip install keras-tuner

     |████████████████████████████████| 61kB 6.8MB/s 
  Created wheel for keras-tuner: filename=keras_tuner-1.0.1-cp36-none-any.whl size=73200 sha256=bf82a49a5f37ae85549d7f6b867c26626778f236ebc63c7302bc6f616b66909e
  Stored in directory: /root/.cache/pip/wheels/b9/cc/62/52716b70dd90f3db12519233c3a93a5360bc672da1a10ded43
  Created wheel for terminaltables: filename=terminaltables-3.1.0-cp36-none-any.whl size=15356 sha256=bc23ff4d1d820bc5585322bdf4da9c6db5b5eaa2205f0e2033350978b10d7063
  Stored in directory: /root/.cache/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
Successfully built keras-tuner terminaltables


In [0]:
'''Reference https://keras-team.github.io/keras-tuner/ and Krish naik
Requirments Python 3.6 TensorFlow 2.0
https://www.tensorflow.org/tutorials/keras/classification'''

In [0]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
print(tf.__version__)

2.2.0-rc2


In [0]:
fashion_mnist = keras.datasets.fashion_mnist

In [4]:
(train_images,train_labels),(test_images,test_labels) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [8]:
train_labels[0]

9

In [0]:
train_images = train_images/255.0
test_images = test_images/255.0

In [25]:
train_images[0].shape

(28, 28, 1)

In [0]:
train_images=train_images.reshape(len(train_images),28,28,1)
test_images=test_images.reshape(len(test_images),28,28,1)

In [12]:
train_images.shape

(60000, 28, 28, 1)

In [0]:
def build_model(hp):  
  model = keras.Sequential([
    keras.layers.Conv2D(
        filters=hp.Int('conv_1_filter', min_value=32, max_value=128, step=16),
        kernel_size=hp.Choice('conv_1_kernel', values = [3,5]),
        activation='relu',
        input_shape=(28,28,1)
    ),
    keras.layers.Conv2D(
        filters=hp.Int('conv_2_filter', min_value=32, max_value=64, step=16),
        kernel_size=hp.Choice('conv_2_kernel', values = [3,5]),
        activation='relu'
    ),
    keras.layers.Flatten(),
    keras.layers.Dense(
        units=hp.Int('dense_1_units', min_value=32, max_value=128, step=16),
        activation='relu'
    ),
    keras.layers.Dense(10, activation='softmax')
  ])
  
  model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate', values=[1e-2, 1e-3])),
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
  
  return model

In [0]:
from kerastuner import RandomSearch
from kerastuner.engine.hyperparameters import HyperParameters

In [0]:
tuner_search = RandomSearch(hypermodel=build_model,objective='val_accuracy',max_trials=5,directory='output',project_name="Mnist Fashion")

In [18]:
tuner_search.search(train_images,train_labels,epochs=5,validation_split=0.1)

Epoch 1/5
1688/1688 [==============================] - 9s 5ms/step - loss: 0.4881 - accuracy: 0.8229 - val_loss: 0.3685 - val_accuracy: 0.8647
Epoch 2/5
1688/1688 [==============================] - 9s 5ms/step - loss: 0.3548 - accuracy: 0.8698 - val_loss: 0.3545 - val_accuracy: 0.8743
Epoch 3/5
1688/1688 [==============================] - 8s 5ms/step - loss: 0.3320 - accuracy: 0.8782 - val_loss: 0.3622 - val_accuracy: 0.8743
Epoch 4/5
1688/1688 [==============================] - 8s 5ms/step - loss: 0.3142 - accuracy: 0.8851 - val_loss: 0.3832 - val_accuracy: 0.8707
Epoch 5/5
1688/1688 [==============================] - 8s 5ms/step - loss: 0.3001 - accuracy: 0.8903 - val_loss: 0.3550 - val_accuracy: 0.8747


Epoch 1/5
1688/1688 [==============================] - 11s 6ms/step - loss: 0.5005 - accuracy: 0.8263 - val_loss: 0.4400 - val_accuracy: 0.8438
Epoch 2/5
1688/1688 [==============================] - 11s 6ms/step - loss: 0.3572 - accuracy: 0.8700 - val_loss: 0.3702 - val_accuracy: 0.8665
Epoch 3/5
1688/1688 [==============================] - 11s 6ms/step - loss: 0.3246 - accuracy: 0.8802 - val_loss: 0.3723 - val_accuracy: 0.8632
Epoch 4/5
1688/1688 [==============================] - 11s 6ms/step - loss: 0.3133 - accuracy: 0.8853 - val_loss: 0.3918 - val_accuracy: 0.8688
Epoch 5/5
1688/1688 [==============================] - 11s 6ms/step - loss: 0.2939 - accuracy: 0.8912 - val_loss: 0.3791 - val_accuracy: 0.8757


Epoch 1/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.4949 - accuracy: 0.8248 - val_loss: 0.3771 - val_accuracy: 0.8572
Epoch 2/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.3610 - accuracy: 0.8676 - val_loss: 0.3662 - val_accuracy: 0.8643
Epoch 3/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.3299 - accuracy: 0.8780 - val_loss: 0.4080 - val_accuracy: 0.8663
Epoch 4/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.3084 - accuracy: 0.8867 - val_loss: 0.3957 - val_accuracy: 0.8680
Epoch 5/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.2873 - accuracy: 0.8950 - val_loss: 0.3773 - val_accuracy: 0.8742


Epoch 1/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.4806 - accuracy: 0.8283 - val_loss: 0.4230 - val_accuracy: 0.8432
Epoch 2/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.3655 - accuracy: 0.8654 - val_loss: 0.3703 - val_accuracy: 0.8657
Epoch 3/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.3298 - accuracy: 0.8796 - val_loss: 0.4089 - val_accuracy: 0.8677
Epoch 4/5
1688/1688 [==============================] - 10s 6ms/step - loss: 0.3022 - accuracy: 0.8882 - val_loss: 0.3427 - val_accuracy: 0.8785
Epoch 5/5
1688/1688 [==============================] - 11s 6ms/step - loss: 0.2782 - accuracy: 0.8981 - val_loss: 0.3956 - val_accuracy: 0.8767


Epoch 1/5
1688/1688 [==============================] - 10s 6ms/step - loss: 2.3134 - accuracy: 0.1017 - val_loss: 2.3032 - val_accuracy: 0.1050
Epoch 2/5
1688/1688 [==============================] - 10s 6ms/step - loss: 2.3039 - accuracy: 0.0989 - val_loss: 2.3038 - val_accuracy: 0.0925
Epoch 3/5
1688/1688 [==============================] - 10s 6ms/step - loss: 2.3040 - accuracy: 0.1004 - val_loss: 2.3044 - val_accuracy: 0.1003
Epoch 4/5
1688/1688 [==============================] - 10s 6ms/step - loss: 2.3039 - accuracy: 0.1013 - val_loss: 2.3027 - val_accuracy: 0.1050
Epoch 5/5
1688/1688 [==============================] - 10s 6ms/step - loss: 2.3039 - accuracy: 0.1000 - val_loss: 2.3042 - val_accuracy: 0.0942


INFO:tensorflow:Oracle triggered exit


In [0]:
model=tuner_search.get_best_models(num_models=1)[0]

In [20]:
model

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 80)        800       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 22, 22, 32)        64032     
_________________________________________________________________
flatten (Flatten)            (None, 15488)             0         
_________________________________________________________________
dense (Dense)                (None, 80)                1239120   
_________________________________________________________________
dense_1 (Dense)              (None, 10)                810       
Total params: 1,304,762
Trainable params: 1,304,762
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.fit(train_images, train_labels, epochs=10, validation_split=0.1, initial_epoch=5)

Epoch 6/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.2829 - accuracy: 0.8956 - val_loss: 0.3665 - val_accuracy: 0.8732
Epoch 7/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.2708 - accuracy: 0.9016 - val_loss: 0.3864 - val_accuracy: 0.8757
Epoch 8/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.2575 - accuracy: 0.9047 - val_loss: 0.4014 - val_accuracy: 0.8757
Epoch 9/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.2449 - accuracy: 0.9102 - val_loss: 0.4151 - val_accuracy: 0.8805
Epoch 10/10
1688/1688 [==============================] - 10s 6ms/step - loss: 0.2310 - accuracy: 0.9169 - val_loss: 0.4149 - val_accuracy: 0.8695


In [33]:
p=np.argmax(model.predict(test_images), axis=-1)
p

array([9, 2, 1, ..., 8, 1, 5])

In [34]:
test_labels

array([9, 2, 1, ..., 8, 1, 5], dtype=uint8)

In [36]:
model.predict_classes(test_images)

array([9, 2, 1, ..., 8, 1, 5])